// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	fs "io/fs"

	mock "github.com/stretchr/testify/mock"
)

// MockFilepathWalkFunc is an autogenerated mock type for the FilepathWalkFunc type
type MockFilepathWalkFunc struct {
	mock.Mock
}

type MockFilepathWalkFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilepathWalkFunc) EXPECT() *MockFilepathWalkFunc_Expecter {
	return &MockFilepathWalkFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: path, info, err
func (_m *MockFilepathWalkFunc) Execute(path string, info fs.FileInfo, err error) error {
	ret := _m.Called(path, info, err)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fs.FileInfo, error) error); ok {
		r0 = rf(path, info, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFilepathWalkFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilepathWalkFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - path string
//   - info fs.FileInfo
//   - err error
func (_e *MockFilepathWalkFunc_Expecter) Execute(path interface{}, info interface{}, err interface{}) *MockFilepathWalkFunc_Execute_Call {
	return &MockFilepathWalkFunc_Execute_Call{Call: _e.mock.On("Execute", path, info, err)}
}

func (_c *MockFilepathWalkFunc_Execute_Call) Run(run func(path string, info fs.FileInfo, err error)) *MockFilepathWalkFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(fs.FileInfo), args[2].(error))
	})
	return _c
}

func (_c *MockFilepathWalkFunc_Execute_Call) Return(_a0 error) *MockFilepathWalkFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFilepathWalkFunc_Execute_Call) RunAndReturn(run func(string, fs.FileInfo, error) error) *MockFilepathWalkFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilepathWalkFunc creates a new instance of MockFilepathWalkFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilepathWalkFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilepathWalkFunc {
	mock := &MockFilepathWalkFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
