// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ast "go/ast"

	model "github.com/mouse-blink/gooze/internal/model"
	mock "github.com/stretchr/testify/mock"

	token "go/token"
)

// MockGoFileAdapter is an autogenerated mock type for the GoFileAdapter type
type MockGoFileAdapter struct {
	mock.Mock
}

type MockGoFileAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoFileAdapter) EXPECT() *MockGoFileAdapter_Expecter {
	return &MockGoFileAdapter_Expecter{mock: &_m.Mock}
}

// ExtractScopes provides a mock function with given fields: fileSet, file
func (_m *MockGoFileAdapter) ExtractScopes(fileSet *token.FileSet, file *ast.File) []model.CodeScope {
	ret := _m.Called(fileSet, file)

	if len(ret) == 0 {
		panic("no return value specified for ExtractScopes")
	}

	var r0 []model.CodeScope
	if rf, ok := ret.Get(0).(func(*token.FileSet, *ast.File) []model.CodeScope); ok {
		r0 = rf(fileSet, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CodeScope)
		}
	}

	return r0
}

// MockGoFileAdapter_ExtractScopes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractScopes'
type MockGoFileAdapter_ExtractScopes_Call struct {
	*mock.Call
}

// ExtractScopes is a helper method to define mock.On call
//   - fileSet *token.FileSet
//   - file *ast.File
func (_e *MockGoFileAdapter_Expecter) ExtractScopes(fileSet interface{}, file interface{}) *MockGoFileAdapter_ExtractScopes_Call {
	return &MockGoFileAdapter_ExtractScopes_Call{Call: _e.mock.On("ExtractScopes", fileSet, file)}
}

func (_c *MockGoFileAdapter_ExtractScopes_Call) Run(run func(fileSet *token.FileSet, file *ast.File)) *MockGoFileAdapter_ExtractScopes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*token.FileSet), args[1].(*ast.File))
	})
	return _c
}

func (_c *MockGoFileAdapter_ExtractScopes_Call) Return(_a0 []model.CodeScope) *MockGoFileAdapter_ExtractScopes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoFileAdapter_ExtractScopes_Call) RunAndReturn(run func(*token.FileSet, *ast.File) []model.CodeScope) *MockGoFileAdapter_ExtractScopes_Call {
	_c.Call.Return(run)
	return _c
}

// FunctionLines provides a mock function with given fields: scopes
func (_m *MockGoFileAdapter) FunctionLines(scopes []model.CodeScope) []int {
	ret := _m.Called(scopes)

	if len(ret) == 0 {
		panic("no return value specified for FunctionLines")
	}

	var r0 []int
	if rf, ok := ret.Get(0).(func([]model.CodeScope) []int); ok {
		r0 = rf(scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	return r0
}

// MockGoFileAdapter_FunctionLines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FunctionLines'
type MockGoFileAdapter_FunctionLines_Call struct {
	*mock.Call
}

// FunctionLines is a helper method to define mock.On call
//   - scopes []model.CodeScope
func (_e *MockGoFileAdapter_Expecter) FunctionLines(scopes interface{}) *MockGoFileAdapter_FunctionLines_Call {
	return &MockGoFileAdapter_FunctionLines_Call{Call: _e.mock.On("FunctionLines", scopes)}
}

func (_c *MockGoFileAdapter_FunctionLines_Call) Run(run func(scopes []model.CodeScope)) *MockGoFileAdapter_FunctionLines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.CodeScope))
	})
	return _c
}

func (_c *MockGoFileAdapter_FunctionLines_Call) Return(_a0 []int) *MockGoFileAdapter_FunctionLines_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoFileAdapter_FunctionLines_Call) RunAndReturn(run func([]model.CodeScope) []int) *MockGoFileAdapter_FunctionLines_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function with given fields: fileSet, filename, src
func (_m *MockGoFileAdapter) Parse(fileSet *token.FileSet, filename string, src []byte) (*ast.File, error) {
	ret := _m.Called(fileSet, filename, src)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *ast.File
	var r1 error
	if rf, ok := ret.Get(0).(func(*token.FileSet, string, []byte) (*ast.File, error)); ok {
		return rf(fileSet, filename, src)
	}
	if rf, ok := ret.Get(0).(func(*token.FileSet, string, []byte) *ast.File); ok {
		r0 = rf(fileSet, filename, src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ast.File)
		}
	}

	if rf, ok := ret.Get(1).(func(*token.FileSet, string, []byte) error); ok {
		r1 = rf(fileSet, filename, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoFileAdapter_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockGoFileAdapter_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - fileSet *token.FileSet
//   - filename string
//   - src []byte
func (_e *MockGoFileAdapter_Expecter) Parse(fileSet interface{}, filename interface{}, src interface{}) *MockGoFileAdapter_Parse_Call {
	return &MockGoFileAdapter_Parse_Call{Call: _e.mock.On("Parse", fileSet, filename, src)}
}

func (_c *MockGoFileAdapter_Parse_Call) Run(run func(fileSet *token.FileSet, filename string, src []byte)) *MockGoFileAdapter_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*token.FileSet), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockGoFileAdapter_Parse_Call) Return(_a0 *ast.File, _a1 error) *MockGoFileAdapter_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoFileAdapter_Parse_Call) RunAndReturn(run func(*token.FileSet, string, []byte) (*ast.File, error)) *MockGoFileAdapter_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ScopeForLine provides a mock function with given fields: scopes, line
func (_m *MockGoFileAdapter) ScopeForLine(scopes []model.CodeScope, line int) model.ScopeType {
	ret := _m.Called(scopes, line)

	if len(ret) == 0 {
		panic("no return value specified for ScopeForLine")
	}

	var r0 model.ScopeType
	if rf, ok := ret.Get(0).(func([]model.CodeScope, int) model.ScopeType); ok {
		r0 = rf(scopes, line)
	} else {
		r0 = ret.Get(0).(model.ScopeType)
	}

	return r0
}

// MockGoFileAdapter_ScopeForLine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScopeForLine'
type MockGoFileAdapter_ScopeForLine_Call struct {
	*mock.Call
}

// ScopeForLine is a helper method to define mock.On call
//   - scopes []model.CodeScope
//   - line int
func (_e *MockGoFileAdapter_Expecter) ScopeForLine(scopes interface{}, line interface{}) *MockGoFileAdapter_ScopeForLine_Call {
	return &MockGoFileAdapter_ScopeForLine_Call{Call: _e.mock.On("ScopeForLine", scopes, line)}
}

func (_c *MockGoFileAdapter_ScopeForLine_Call) Run(run func(scopes []model.CodeScope, line int)) *MockGoFileAdapter_ScopeForLine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]model.CodeScope), args[1].(int))
	})
	return _c
}

func (_c *MockGoFileAdapter_ScopeForLine_Call) Return(_a0 model.ScopeType) *MockGoFileAdapter_ScopeForLine_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGoFileAdapter_ScopeForLine_Call) RunAndReturn(run func([]model.CodeScope, int) model.ScopeType) *MockGoFileAdapter_ScopeForLine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoFileAdapter creates a new instance of MockGoFileAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoFileAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoFileAdapter {
	mock := &MockGoFileAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
