// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	adapter "gooze.dev/pkg/gooze/internal/adapter"
	model "gooze.dev/pkg/gooze/internal/model"
)

// MockOCIRegistry is an autogenerated mock type for the OCIRegistry type
type MockOCIRegistry struct {
	mock.Mock
}

type MockOCIRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOCIRegistry) EXPECT() *MockOCIRegistry_Expecter {
	return &MockOCIRegistry_Expecter{mock: &_m.Mock}
}

// Pull provides a mock function with given fields: ctx, ref, dir, opts
func (_m *MockOCIRegistry) Pull(ctx context.Context, ref string, dir model.Path, opts adapter.RegistryOptions) error {
	ret := _m.Called(ctx, ref, dir, opts)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Path, adapter.RegistryOptions) error); ok {
		r0 = rf(ctx, ref, dir, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOCIRegistry_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockOCIRegistry_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - dir model.Path
//   - opts adapter.RegistryOptions
func (_e *MockOCIRegistry_Expecter) Pull(ctx interface{}, ref interface{}, dir interface{}, opts interface{}) *MockOCIRegistry_Pull_Call {
	return &MockOCIRegistry_Pull_Call{Call: _e.mock.On("Pull", ctx, ref, dir, opts)}
}

func (_c *MockOCIRegistry_Pull_Call) Run(run func(ctx context.Context, ref string, dir model.Path, opts adapter.RegistryOptions)) *MockOCIRegistry_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.Path), args[3].(adapter.RegistryOptions))
	})
	return _c
}

func (_c *MockOCIRegistry_Pull_Call) Return(_a0 error) *MockOCIRegistry_Pull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOCIRegistry_Pull_Call) RunAndReturn(run func(context.Context, string, model.Path, adapter.RegistryOptions) error) *MockOCIRegistry_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: ctx, ref, dir, opts
func (_m *MockOCIRegistry) Push(ctx context.Context, ref string, dir model.Path, opts adapter.RegistryOptions) error {
	ret := _m.Called(ctx, ref, dir, opts)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.Path, adapter.RegistryOptions) error); ok {
		r0 = rf(ctx, ref, dir, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOCIRegistry_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockOCIRegistry_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - dir model.Path
//   - opts adapter.RegistryOptions
func (_e *MockOCIRegistry_Expecter) Push(ctx interface{}, ref interface{}, dir interface{}, opts interface{}) *MockOCIRegistry_Push_Call {
	return &MockOCIRegistry_Push_Call{Call: _e.mock.On("Push", ctx, ref, dir, opts)}
}

func (_c *MockOCIRegistry_Push_Call) Run(run func(ctx context.Context, ref string, dir model.Path, opts adapter.RegistryOptions)) *MockOCIRegistry_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.Path), args[3].(adapter.RegistryOptions))
	})
	return _c
}

func (_c *MockOCIRegistry_Push_Call) Return(_a0 error) *MockOCIRegistry_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOCIRegistry_Push_Call) RunAndReturn(run func(context.Context, string, model.Path, adapter.RegistryOptions) error) *MockOCIRegistry_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOCIRegistry creates a new instance of MockOCIRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOCIRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOCIRegistry {
	mock := &MockOCIRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
