// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTestRunnerAdapter is an autogenerated mock type for the TestRunnerAdapter type
type MockTestRunnerAdapter struct {
	mock.Mock
}

type MockTestRunnerAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTestRunnerAdapter) EXPECT() *MockTestRunnerAdapter_Expecter {
	return &MockTestRunnerAdapter_Expecter{mock: &_m.Mock}
}

// RunGoTest provides a mock function with given fields: ctx, workDir, testFile
func (_m *MockTestRunnerAdapter) RunGoTest(ctx context.Context, workDir string, testFile string) (string, error) {
	ret := _m.Called(ctx, workDir, testFile)

	if len(ret) == 0 {
		panic("no return value specified for RunGoTest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, workDir, testFile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, workDir, testFile)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, workDir, testFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTestRunnerAdapter_RunGoTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunGoTest'
type MockTestRunnerAdapter_RunGoTest_Call struct {
	*mock.Call
}

// RunGoTest is a helper method to define mock.On call
//   - ctx context.Context
//   - workDir string
//   - testFile string
func (_e *MockTestRunnerAdapter_Expecter) RunGoTest(ctx interface{}, workDir interface{}, testFile interface{}) *MockTestRunnerAdapter_RunGoTest_Call {
	return &MockTestRunnerAdapter_RunGoTest_Call{Call: _e.mock.On("RunGoTest", ctx, workDir, testFile)}
}

func (_c *MockTestRunnerAdapter_RunGoTest_Call) Run(run func(ctx context.Context, workDir string, testFile string)) *MockTestRunnerAdapter_RunGoTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTestRunnerAdapter_RunGoTest_Call) Return(output string, err error) *MockTestRunnerAdapter_RunGoTest_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *MockTestRunnerAdapter_RunGoTest_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockTestRunnerAdapter_RunGoTest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTestRunnerAdapter creates a new instance of MockTestRunnerAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTestRunnerAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTestRunnerAdapter {
	mock := &MockTestRunnerAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
