// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "gooze.dev/pkg/gooze/internal/model"
)

// MockFilesAdapter is an autogenerated mock type for the FilesAdapter type
type MockFilesAdapter struct {
	mock.Mock
}

type MockFilesAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesAdapter) EXPECT() *MockFilesAdapter_Expecter {
	return &MockFilesAdapter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, rootDirs, parallel, exclude
func (_m *MockFilesAdapter) Get(ctx context.Context, rootDirs []model.Path, parallel int, exclude ...string) (<-chan model.Source, error) {
	_va := make([]interface{}, len(exclude))
	for _i := range exclude {
		_va[_i] = exclude[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, rootDirs, parallel)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 <-chan model.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Path, int, ...string) (<-chan model.Source, error)); ok {
		return rf(ctx, rootDirs, parallel, exclude...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.Path, int, ...string) <-chan model.Source); ok {
		r0 = rf(ctx, rootDirs, parallel, exclude...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.Path, int, ...string) error); ok {
		r1 = rf(ctx, rootDirs, parallel, exclude...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilesAdapter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFilesAdapter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - rootDirs []model.Path
//   - parallel int
//   - exclude ...string
func (_e *MockFilesAdapter_Expecter) Get(ctx interface{}, rootDirs interface{}, parallel interface{}, exclude ...interface{}) *MockFilesAdapter_Get_Call {
	return &MockFilesAdapter_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, rootDirs, parallel}, exclude...)...)}
}

func (_c *MockFilesAdapter_Get_Call) Run(run func(ctx context.Context, rootDirs []model.Path, parallel int, exclude ...string)) *MockFilesAdapter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].([]model.Path), args[2].(int), variadicArgs...)
	})
	return _c
}

func (_c *MockFilesAdapter_Get_Call) Return(_a0 <-chan model.Source, _a1 error) *MockFilesAdapter_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilesAdapter_Get_Call) RunAndReturn(run func(context.Context, []model.Path, int, ...string) (<-chan model.Source, error)) *MockFilesAdapter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: ctx, path
func (_m *MockFilesAdapter) ReadFile(ctx context.Context, path model.Path) ([]byte, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Path) ([]byte, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Path) []byte); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Path) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFilesAdapter_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockFilesAdapter_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - path model.Path
func (_e *MockFilesAdapter_Expecter) ReadFile(ctx interface{}, path interface{}) *MockFilesAdapter_ReadFile_Call {
	return &MockFilesAdapter_ReadFile_Call{Call: _e.mock.On("ReadFile", ctx, path)}
}

func (_c *MockFilesAdapter_ReadFile_Call) Run(run func(ctx context.Context, path model.Path)) *MockFilesAdapter_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Path))
	})
	return _c
}

func (_c *MockFilesAdapter_ReadFile_Call) Return(_a0 []byte, _a1 error) *MockFilesAdapter_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFilesAdapter_ReadFile_Call) RunAndReturn(run func(context.Context, model.Path) ([]byte, error)) *MockFilesAdapter_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFilesAdapter creates a new instance of MockFilesAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesAdapter {
	mock := &MockFilesAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
