// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	ast "go/ast"

	mock "github.com/stretchr/testify/mock"

	token "go/token"
)

// MockGoFileAdapter is an autogenerated mock type for the GoFileAdapter type
type MockGoFileAdapter struct {
	mock.Mock
}

type MockGoFileAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoFileAdapter) EXPECT() *MockGoFileAdapter_Expecter {
	return &MockGoFileAdapter_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: ctx, fileSet, filename, src
func (_m *MockGoFileAdapter) Parse(ctx context.Context, fileSet *token.FileSet, filename string, src []byte) (*ast.File, error) {
	ret := _m.Called(ctx, fileSet, filename, src)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *ast.File
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *token.FileSet, string, []byte) (*ast.File, error)); ok {
		return rf(ctx, fileSet, filename, src)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *token.FileSet, string, []byte) *ast.File); ok {
		r0 = rf(ctx, fileSet, filename, src)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ast.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *token.FileSet, string, []byte) error); ok {
		r1 = rf(ctx, fileSet, filename, src)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGoFileAdapter_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockGoFileAdapter_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - fileSet *token.FileSet
//   - filename string
//   - src []byte
func (_e *MockGoFileAdapter_Expecter) Parse(ctx interface{}, fileSet interface{}, filename interface{}, src interface{}) *MockGoFileAdapter_Parse_Call {
	return &MockGoFileAdapter_Parse_Call{Call: _e.mock.On("Parse", ctx, fileSet, filename, src)}
}

func (_c *MockGoFileAdapter_Parse_Call) Run(run func(ctx context.Context, fileSet *token.FileSet, filename string, src []byte)) *MockGoFileAdapter_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*token.FileSet), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockGoFileAdapter_Parse_Call) Return(_a0 *ast.File, _a1 error) *MockGoFileAdapter_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGoFileAdapter_Parse_Call) RunAndReturn(run func(context.Context, *token.FileSet, string, []byte) (*ast.File, error)) *MockGoFileAdapter_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGoFileAdapter creates a new instance of MockGoFileAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoFileAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoFileAdapter {
	mock := &MockGoFileAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
