// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "gooze.dev/pkg/gooze/internal/domain"
	model "gooze.dev/pkg/gooze/internal/model"
)

// MockReporter is an autogenerated mock type for the Reporter type
type MockReporter struct {
	mock.Mock
}

type MockReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReporter) EXPECT() *MockReporter_Expecter {
	return &MockReporter_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockReporter) Close(ctx context.Context) {
	_m.Called(ctx)
}

// MockReporter_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockReporter_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReporter_Expecter) Close(ctx interface{}) *MockReporter_Close_Call {
	return &MockReporter_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockReporter_Close_Call) Run(run func(ctx context.Context)) *MockReporter_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReporter_Close_Call) Return() *MockReporter_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Close_Call) RunAndReturn(run func(context.Context)) *MockReporter_Close_Call {
	_c.Run(run)
	return _c
}

// DisplayCompletedTestInfo provides a mock function with given fields: ctx, mutation, result
func (_m *MockReporter) DisplayCompletedTestInfo(ctx context.Context, mutation model.Mutation, result model.Result) {
	_m.Called(ctx, mutation, result)
}

// MockReporter_DisplayCompletedTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayCompletedTestInfo'
type MockReporter_DisplayCompletedTestInfo_Call struct {
	*mock.Call
}

// DisplayCompletedTestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - mutation model.Mutation
//   - result model.Result
func (_e *MockReporter_Expecter) DisplayCompletedTestInfo(ctx interface{}, mutation interface{}, result interface{}) *MockReporter_DisplayCompletedTestInfo_Call {
	return &MockReporter_DisplayCompletedTestInfo_Call{Call: _e.mock.On("DisplayCompletedTestInfo", ctx, mutation, result)}
}

func (_c *MockReporter_DisplayCompletedTestInfo_Call) Run(run func(ctx context.Context, mutation model.Mutation, result model.Result)) *MockReporter_DisplayCompletedTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mutation), args[2].(model.Result))
	})
	return _c
}

func (_c *MockReporter_DisplayCompletedTestInfo_Call) Return() *MockReporter_DisplayCompletedTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_DisplayCompletedTestInfo_Call) RunAndReturn(run func(context.Context, model.Mutation, model.Result)) *MockReporter_DisplayCompletedTestInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayConcurrencyInfo provides a mock function with given fields: ctx, threads, shardIndex, shardCount
func (_m *MockReporter) DisplayConcurrencyInfo(ctx context.Context, threads int, shardIndex int, shardCount int) {
	_m.Called(ctx, threads, shardIndex, shardCount)
}

// MockReporter_DisplayConcurrencyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayConcurrencyInfo'
type MockReporter_DisplayConcurrencyInfo_Call struct {
	*mock.Call
}

// DisplayConcurrencyInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - threads int
//   - shardIndex int
//   - shardCount int
func (_e *MockReporter_Expecter) DisplayConcurrencyInfo(ctx interface{}, threads interface{}, shardIndex interface{}, shardCount interface{}) *MockReporter_DisplayConcurrencyInfo_Call {
	return &MockReporter_DisplayConcurrencyInfo_Call{Call: _e.mock.On("DisplayConcurrencyInfo", ctx, threads, shardIndex, shardCount)}
}

func (_c *MockReporter_DisplayConcurrencyInfo_Call) Run(run func(ctx context.Context, threads int, shardIndex int, shardCount int)) *MockReporter_DisplayConcurrencyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockReporter_DisplayConcurrencyInfo_Call) Return() *MockReporter_DisplayConcurrencyInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_DisplayConcurrencyInfo_Call) RunAndReturn(run func(context.Context, int, int, int)) *MockReporter_DisplayConcurrencyInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayEstimation provides a mock function with given fields: ctx, estimation, err
func (_m *MockReporter) DisplayEstimation(ctx context.Context, estimation domain.Estimation, err error) error {
	ret := _m.Called(ctx, estimation, err)

	if len(ret) == 0 {
		panic("no return value specified for DisplayEstimation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Estimation, error) error); ok {
		r0 = rf(ctx, estimation, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReporter_DisplayEstimation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayEstimation'
type MockReporter_DisplayEstimation_Call struct {
	*mock.Call
}

// DisplayEstimation is a helper method to define mock.On call
//   - ctx context.Context
//   - estimation domain.Estimation
//   - err error
func (_e *MockReporter_Expecter) DisplayEstimation(ctx interface{}, estimation interface{}, err interface{}) *MockReporter_DisplayEstimation_Call {
	return &MockReporter_DisplayEstimation_Call{Call: _e.mock.On("DisplayEstimation", ctx, estimation, err)}
}

func (_c *MockReporter_DisplayEstimation_Call) Run(run func(ctx context.Context, estimation domain.Estimation, err error)) *MockReporter_DisplayEstimation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Estimation), args[2].(error))
	})
	return _c
}

func (_c *MockReporter_DisplayEstimation_Call) Return(_a0 error) *MockReporter_DisplayEstimation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReporter_DisplayEstimation_Call) RunAndReturn(run func(context.Context, domain.Estimation, error) error) *MockReporter_DisplayEstimation_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayMutationScore provides a mock function with given fields: ctx, score
func (_m *MockReporter) DisplayMutationScore(ctx context.Context, score float64) {
	_m.Called(ctx, score)
}

// MockReporter_DisplayMutationScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMutationScore'
type MockReporter_DisplayMutationScore_Call struct {
	*mock.Call
}

// DisplayMutationScore is a helper method to define mock.On call
//   - ctx context.Context
//   - score float64
func (_e *MockReporter_Expecter) DisplayMutationScore(ctx interface{}, score interface{}) *MockReporter_DisplayMutationScore_Call {
	return &MockReporter_DisplayMutationScore_Call{Call: _e.mock.On("DisplayMutationScore", ctx, score)}
}

func (_c *MockReporter_DisplayMutationScore_Call) Run(run func(ctx context.Context, score float64)) *MockReporter_DisplayMutationScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64))
	})
	return _c
}

func (_c *MockReporter_DisplayMutationScore_Call) Return() *MockReporter_DisplayMutationScore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_DisplayMutationScore_Call) RunAndReturn(run func(context.Context, float64)) *MockReporter_DisplayMutationScore_Call {
	_c.Run(run)
	return _c
}

// DisplayStartingTestInfo provides a mock function with given fields: ctx, mutation, threadID
func (_m *MockReporter) DisplayStartingTestInfo(ctx context.Context, mutation model.Mutation, threadID int) {
	_m.Called(ctx, mutation, threadID)
}

// MockReporter_DisplayStartingTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayStartingTestInfo'
type MockReporter_DisplayStartingTestInfo_Call struct {
	*mock.Call
}

// DisplayStartingTestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - mutation model.Mutation
//   - threadID int
func (_e *MockReporter_Expecter) DisplayStartingTestInfo(ctx interface{}, mutation interface{}, threadID interface{}) *MockReporter_DisplayStartingTestInfo_Call {
	return &MockReporter_DisplayStartingTestInfo_Call{Call: _e.mock.On("DisplayStartingTestInfo", ctx, mutation, threadID)}
}

func (_c *MockReporter_DisplayStartingTestInfo_Call) Run(run func(ctx context.Context, mutation model.Mutation, threadID int)) *MockReporter_DisplayStartingTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mutation), args[2].(int))
	})
	return _c
}

func (_c *MockReporter_DisplayStartingTestInfo_Call) Return() *MockReporter_DisplayStartingTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_DisplayStartingTestInfo_Call) RunAndReturn(run func(context.Context, model.Mutation, int)) *MockReporter_DisplayStartingTestInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayUpcomingTestsInfo provides a mock function with given fields: ctx, total
func (_m *MockReporter) DisplayUpcomingTestsInfo(ctx context.Context, total int) {
	_m.Called(ctx, total)
}

// MockReporter_DisplayUpcomingTestsInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayUpcomingTestsInfo'
type MockReporter_DisplayUpcomingTestsInfo_Call struct {
	*mock.Call
}

// DisplayUpcomingTestsInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - total int
func (_e *MockReporter_Expecter) DisplayUpcomingTestsInfo(ctx interface{}, total interface{}) *MockReporter_DisplayUpcomingTestsInfo_Call {
	return &MockReporter_DisplayUpcomingTestsInfo_Call{Call: _e.mock.On("DisplayUpcomingTestsInfo", ctx, total)}
}

func (_c *MockReporter_DisplayUpcomingTestsInfo_Call) Run(run func(ctx context.Context, total int)) *MockReporter_DisplayUpcomingTestsInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockReporter_DisplayUpcomingTestsInfo_Call) Return() *MockReporter_DisplayUpcomingTestsInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_DisplayUpcomingTestsInfo_Call) RunAndReturn(run func(context.Context, int)) *MockReporter_DisplayUpcomingTestsInfo_Call {
	_c.Run(run)
	return _c
}

// StartEstimate provides a mock function with given fields: ctx
func (_m *MockReporter) StartEstimate(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartEstimate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReporter_StartEstimate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEstimate'
type MockReporter_StartEstimate_Call struct {
	*mock.Call
}

// StartEstimate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReporter_Expecter) StartEstimate(ctx interface{}) *MockReporter_StartEstimate_Call {
	return &MockReporter_StartEstimate_Call{Call: _e.mock.On("StartEstimate", ctx)}
}

func (_c *MockReporter_StartEstimate_Call) Run(run func(ctx context.Context)) *MockReporter_StartEstimate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReporter_StartEstimate_Call) Return(_a0 error) *MockReporter_StartEstimate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReporter_StartEstimate_Call) RunAndReturn(run func(context.Context) error) *MockReporter_StartEstimate_Call {
	_c.Call.Return(run)
	return _c
}

// StartTest provides a mock function with given fields: ctx
func (_m *MockReporter) StartTest(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartTest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReporter_StartTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTest'
type MockReporter_StartTest_Call struct {
	*mock.Call
}

// StartTest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReporter_Expecter) StartTest(ctx interface{}) *MockReporter_StartTest_Call {
	return &MockReporter_StartTest_Call{Call: _e.mock.On("StartTest", ctx)}
}

func (_c *MockReporter_StartTest_Call) Run(run func(ctx context.Context)) *MockReporter_StartTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReporter_StartTest_Call) Return(_a0 error) *MockReporter_StartTest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReporter_StartTest_Call) RunAndReturn(run func(context.Context) error) *MockReporter_StartTest_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: ctx
func (_m *MockReporter) Wait(ctx context.Context) {
	_m.Called(ctx)
}

// MockReporter_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockReporter_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReporter_Expecter) Wait(ctx interface{}) *MockReporter_Wait_Call {
	return &MockReporter_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockReporter_Wait_Call) Run(run func(ctx context.Context)) *MockReporter_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReporter_Wait_Call) Return() *MockReporter_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReporter_Wait_Call) RunAndReturn(run func(context.Context)) *MockReporter_Wait_Call {
	_c.Run(run)
	return _c
}

// NewMockReporter creates a new instance of MockReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReporter {
	mock := &MockReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
