// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "gooze.dev/pkg/gooze/internal/model"
)

// MockMutationStreamer is an autogenerated mock type for the MutationStreamer type
type MockMutationStreamer struct {
	mock.Mock
}

type MockMutationStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMutationStreamer) EXPECT() *MockMutationStreamer_Expecter {
	return &MockMutationStreamer_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, paths, exclude, threads
func (_m *MockMutationStreamer) Get(ctx context.Context, paths []model.Path, exclude []string, threads int) <-chan model.Mutation {
	ret := _m.Called(ctx, paths, exclude, threads)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 <-chan model.Mutation
	if rf, ok := ret.Get(0).(func(context.Context, []model.Path, []string, int) <-chan model.Mutation); ok {
		r0 = rf(ctx, paths, exclude, threads)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.Mutation)
		}
	}

	return r0
}

// MockMutationStreamer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMutationStreamer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - paths []model.Path
//   - exclude []string
//   - threads int
func (_e *MockMutationStreamer_Expecter) Get(ctx interface{}, paths interface{}, exclude interface{}, threads interface{}) *MockMutationStreamer_Get_Call {
	return &MockMutationStreamer_Get_Call{Call: _e.mock.On("Get", ctx, paths, exclude, threads)}
}

func (_c *MockMutationStreamer_Get_Call) Run(run func(ctx context.Context, paths []model.Path, exclude []string, threads int)) *MockMutationStreamer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.Path), args[2].([]string), args[3].(int))
	})
	return _c
}

func (_c *MockMutationStreamer_Get_Call) Return(_a0 <-chan model.Mutation) *MockMutationStreamer_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMutationStreamer_Get_Call) RunAndReturn(run func(context.Context, []model.Path, []string, int) <-chan model.Mutation) *MockMutationStreamer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ShardMutations provides a mock function with given fields: ctx, allMutations, threads, shardIndex, totalShardCount
func (_m *MockMutationStreamer) ShardMutations(ctx context.Context, allMutations <-chan model.Mutation, threads int, shardIndex int, totalShardCount int) <-chan model.Mutation {
	ret := _m.Called(ctx, allMutations, threads, shardIndex, totalShardCount)

	if len(ret) == 0 {
		panic("no return value specified for ShardMutations")
	}

	var r0 <-chan model.Mutation
	if rf, ok := ret.Get(0).(func(context.Context, <-chan model.Mutation, int, int, int) <-chan model.Mutation); ok {
		r0 = rf(ctx, allMutations, threads, shardIndex, totalShardCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.Mutation)
		}
	}

	return r0
}

// MockMutationStreamer_ShardMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShardMutations'
type MockMutationStreamer_ShardMutations_Call struct {
	*mock.Call
}

// ShardMutations is a helper method to define mock.On call
//   - ctx context.Context
//   - allMutations <-chan model.Mutation
//   - threads int
//   - shardIndex int
//   - totalShardCount int
func (_e *MockMutationStreamer_Expecter) ShardMutations(ctx interface{}, allMutations interface{}, threads interface{}, shardIndex interface{}, totalShardCount interface{}) *MockMutationStreamer_ShardMutations_Call {
	return &MockMutationStreamer_ShardMutations_Call{Call: _e.mock.On("ShardMutations", ctx, allMutations, threads, shardIndex, totalShardCount)}
}

func (_c *MockMutationStreamer_ShardMutations_Call) Run(run func(ctx context.Context, allMutations <-chan model.Mutation, threads int, shardIndex int, totalShardCount int)) *MockMutationStreamer_ShardMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(<-chan model.Mutation), args[2].(int), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockMutationStreamer_ShardMutations_Call) Return(_a0 <-chan model.Mutation) *MockMutationStreamer_ShardMutations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMutationStreamer_ShardMutations_Call) RunAndReturn(run func(context.Context, <-chan model.Mutation, int, int, int) <-chan model.Mutation) *MockMutationStreamer_ShardMutations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMutationStreamer creates a new instance of MockMutationStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMutationStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMutationStreamer {
	mock := &MockMutationStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
