// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "gooze.dev/pkg/gooze/internal/domain"

	model "gooze.dev/pkg/gooze/internal/model"
)

// MockWorkflowPipeline is an autogenerated mock type for the WorkflowPipeline type
type MockWorkflowPipeline struct {
	mock.Mock
}

type MockWorkflowPipeline_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowPipeline) EXPECT() *MockWorkflowPipeline_Expecter {
	return &MockWorkflowPipeline_Expecter{mock: &_m.Mock}
}

// Estimate provides a mock function with given fields: ctx, events, options
func (_m *MockWorkflowPipeline) Estimate(ctx context.Context, events model.Events, options domain.EstimateOptions) error {
	ret := _m.Called(ctx, events, options)

	if len(ret) == 0 {
		panic("no return value specified for Estimate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Events, domain.EstimateOptions) error); ok {
		r0 = rf(ctx, events, options)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflowPipeline_Estimate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Estimate'
type MockWorkflowPipeline_Estimate_Call struct {
	*mock.Call
}

// Estimate is a helper method to define mock.On call
//   - ctx context.Context
//   - events model.Events
//   - options domain.EstimateOptions
func (_e *MockWorkflowPipeline_Expecter) Estimate(ctx interface{}, events interface{}, options interface{}) *MockWorkflowPipeline_Estimate_Call {
	return &MockWorkflowPipeline_Estimate_Call{Call: _e.mock.On("Estimate", ctx, events, options)}
}

func (_c *MockWorkflowPipeline_Estimate_Call) Run(run func(ctx context.Context, events model.Events, options domain.EstimateOptions)) *MockWorkflowPipeline_Estimate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Events), args[2].(domain.EstimateOptions))
	})
	return _c
}

func (_c *MockWorkflowPipeline_Estimate_Call) Return(_a0 error) *MockWorkflowPipeline_Estimate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflowPipeline_Estimate_Call) RunAndReturn(run func(context.Context, model.Events, domain.EstimateOptions) error) *MockWorkflowPipeline_Estimate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflowPipeline creates a new instance of MockWorkflowPipeline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowPipeline(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowPipeline {
	mock := &MockWorkflowPipeline{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
