// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "gooze.dev/pkg/gooze/internal/domain"
)

// MockWorkflow is an autogenerated mock type for the Workflow type
type MockWorkflow struct {
	mock.Mock
}

type MockWorkflow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflow) EXPECT() *MockWorkflow_Expecter {
	return &MockWorkflow_Expecter{mock: &_m.Mock}
}

// Estimate provides a mock function with given fields: ctx, args
func (_m *MockWorkflow) Estimate(ctx context.Context, args domain.EstimateArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Estimate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.EstimateArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflow_Estimate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Estimate'
type MockWorkflow_Estimate_Call struct {
	*mock.Call
}

// Estimate is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.EstimateArgs
func (_e *MockWorkflow_Expecter) Estimate(ctx interface{}, args interface{}) *MockWorkflow_Estimate_Call {
	return &MockWorkflow_Estimate_Call{Call: _e.mock.On("Estimate", ctx, args)}
}

func (_c *MockWorkflow_Estimate_Call) Run(run func(ctx context.Context, args domain.EstimateArgs)) *MockWorkflow_Estimate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.EstimateArgs))
	})
	return _c
}

func (_c *MockWorkflow_Estimate_Call) Return(_a0 error) *MockWorkflow_Estimate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflow_Estimate_Call) RunAndReturn(run func(context.Context, domain.EstimateArgs) error) *MockWorkflow_Estimate_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ctx, args
func (_m *MockWorkflow) Merge(ctx context.Context, args domain.MergeArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MergeArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflow_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockWorkflow_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.MergeArgs
func (_e *MockWorkflow_Expecter) Merge(ctx interface{}, args interface{}) *MockWorkflow_Merge_Call {
	return &MockWorkflow_Merge_Call{Call: _e.mock.On("Merge", ctx, args)}
}

func (_c *MockWorkflow_Merge_Call) Run(run func(ctx context.Context, args domain.MergeArgs)) *MockWorkflow_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.MergeArgs))
	})
	return _c
}

func (_c *MockWorkflow_Merge_Call) Return(_a0 error) *MockWorkflow_Merge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflow_Merge_Call) RunAndReturn(run func(context.Context, domain.MergeArgs) error) *MockWorkflow_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function with given fields: ctx, args
func (_m *MockWorkflow) Test(ctx context.Context, args domain.TestArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TestArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflow_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockWorkflow_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.TestArgs
func (_e *MockWorkflow_Expecter) Test(ctx interface{}, args interface{}) *MockWorkflow_Test_Call {
	return &MockWorkflow_Test_Call{Call: _e.mock.On("Test", ctx, args)}
}

func (_c *MockWorkflow_Test_Call) Run(run func(ctx context.Context, args domain.TestArgs)) *MockWorkflow_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TestArgs))
	})
	return _c
}

func (_c *MockWorkflow_Test_Call) Return(_a0 error) *MockWorkflow_Test_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflow_Test_Call) RunAndReturn(run func(context.Context, domain.TestArgs) error) *MockWorkflow_Test_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function with given fields: ctx, args
func (_m *MockWorkflow) View(ctx context.Context, args domain.ViewArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ViewArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkflow_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockWorkflow_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.ViewArgs
func (_e *MockWorkflow_Expecter) View(ctx interface{}, args interface{}) *MockWorkflow_View_Call {
	return &MockWorkflow_View_Call{Call: _e.mock.On("View", ctx, args)}
}

func (_c *MockWorkflow_View_Call) Run(run func(ctx context.Context, args domain.ViewArgs)) *MockWorkflow_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ViewArgs))
	})
	return _c
}

func (_c *MockWorkflow_View_Call) Return(_a0 error) *MockWorkflow_View_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkflow_View_Call) RunAndReturn(run func(context.Context, domain.ViewArgs) error) *MockWorkflow_View_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkflow creates a new instance of MockWorkflow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflow {
	mock := &MockWorkflow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
