// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "gooze.dev/pkg/gooze/internal/model"

	time "time"
)

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator struct {
	mock.Mock
}

type MockOrchestrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator) EXPECT() *MockOrchestrator_Expecter {
	return &MockOrchestrator_Expecter{mock: &_m.Mock}
}

// TestMutation provides a mock function with given fields: mutation
func (_m *MockOrchestrator) TestMutation(mutation model.Mutation) (model.Result, error) {
	ret := _m.Called(mutation)

	if len(ret) == 0 {
		panic("no return value specified for TestMutation")
	}

	var r0 model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Mutation) (model.Result, error)); ok {
		return rf(mutation)
	}
	if rf, ok := ret.Get(0).(func(model.Mutation) model.Result); ok {
		r0 = rf(mutation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Mutation) error); ok {
		r1 = rf(mutation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_TestMutation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestMutation'
type MockOrchestrator_TestMutation_Call struct {
	*mock.Call
}

// TestMutation is a helper method to define mock.On call
//   - mutation model.Mutation
func (_e *MockOrchestrator_Expecter) TestMutation(mutation interface{}) *MockOrchestrator_TestMutation_Call {
	return &MockOrchestrator_TestMutation_Call{Call: _e.mock.On("TestMutation", mutation)}
}

func (_c *MockOrchestrator_TestMutation_Call) Run(run func(mutation model.Mutation)) *MockOrchestrator_TestMutation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Mutation))
	})
	return _c
}

func (_c *MockOrchestrator_TestMutation_Call) Return(_a0 model.Result, _a1 error) *MockOrchestrator_TestMutation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_TestMutation_Call) RunAndReturn(run func(model.Mutation) (model.Result, error)) *MockOrchestrator_TestMutation_Call {
	_c.Call.Return(run)
	return _c
}

// TestMutationWithTimeout provides a mock function with given fields: mutation, timeoutDuration
func (_m *MockOrchestrator) TestMutationWithTimeout(mutation model.Mutation, timeoutDuration time.Duration) (model.Result, error) {
	ret := _m.Called(mutation, timeoutDuration)

	if len(ret) == 0 {
		panic("no return value specified for TestMutationWithTimeout")
	}

	var r0 model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Mutation, time.Duration) (model.Result, error)); ok {
		return rf(mutation, timeoutDuration)
	}
	if rf, ok := ret.Get(0).(func(model.Mutation, time.Duration) model.Result); ok {
		r0 = rf(mutation, timeoutDuration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Mutation, time.Duration) error); ok {
		r1 = rf(mutation, timeoutDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrchestrator_TestMutationWithTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestMutationWithTimeout'
type MockOrchestrator_TestMutationWithTimeout_Call struct {
	*mock.Call
}

// TestMutationWithTimeout is a helper method to define mock.On call
//   - mutation model.Mutation
//   - timeoutDuration time.Duration
func (_e *MockOrchestrator_Expecter) TestMutationWithTimeout(mutation interface{}, timeoutDuration interface{}) *MockOrchestrator_TestMutationWithTimeout_Call {
	return &MockOrchestrator_TestMutationWithTimeout_Call{Call: _e.mock.On("TestMutationWithTimeout", mutation, timeoutDuration)}
}

func (_c *MockOrchestrator_TestMutationWithTimeout_Call) Run(run func(mutation model.Mutation, timeoutDuration time.Duration)) *MockOrchestrator_TestMutationWithTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Mutation), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockOrchestrator_TestMutationWithTimeout_Call) Return(_a0 model.Result, _a1 error) *MockOrchestrator_TestMutationWithTimeout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrchestrator_TestMutationWithTimeout_Call) RunAndReturn(run func(model.Mutation, time.Duration) (model.Result, error)) *MockOrchestrator_TestMutationWithTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator {
	mock := &MockOrchestrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
