// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "gooze.dev/pkg/gooze/internal/domain"
)

// MockReportPublisher is an autogenerated mock type for the ReportPublisher type
type MockReportPublisher struct {
	mock.Mock
}

type MockReportPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportPublisher) EXPECT() *MockReportPublisher_Expecter {
	return &MockReportPublisher_Expecter{mock: &_m.Mock}
}

// Pull provides a mock function with given fields: ctx, args
func (_m *MockReportPublisher) Pull(ctx context.Context, args domain.PullArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PullArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportPublisher_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockReportPublisher_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.PullArgs
func (_e *MockReportPublisher_Expecter) Pull(ctx interface{}, args interface{}) *MockReportPublisher_Pull_Call {
	return &MockReportPublisher_Pull_Call{Call: _e.mock.On("Pull", ctx, args)}
}

func (_c *MockReportPublisher_Pull_Call) Run(run func(ctx context.Context, args domain.PullArgs)) *MockReportPublisher_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PullArgs))
	})
	return _c
}

func (_c *MockReportPublisher_Pull_Call) Return(_a0 error) *MockReportPublisher_Pull_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportPublisher_Pull_Call) RunAndReturn(run func(context.Context, domain.PullArgs) error) *MockReportPublisher_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function with given fields: ctx, args
func (_m *MockReportPublisher) Push(ctx context.Context, args domain.PushArgs) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PushArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportPublisher_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockReportPublisher_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - args domain.PushArgs
func (_e *MockReportPublisher_Expecter) Push(ctx interface{}, args interface{}) *MockReportPublisher_Push_Call {
	return &MockReportPublisher_Push_Call{Call: _e.mock.On("Push", ctx, args)}
}

func (_c *MockReportPublisher_Push_Call) Run(run func(ctx context.Context, args domain.PushArgs)) *MockReportPublisher_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PushArgs))
	})
	return _c
}

func (_c *MockReportPublisher_Push_Call) Return(_a0 error) *MockReportPublisher_Push_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportPublisher_Push_Call) RunAndReturn(run func(context.Context, domain.PushArgs) error) *MockReportPublisher_Push_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportPublisher creates a new instance of MockReportPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportPublisher {
	mock := &MockReportPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
