// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "gooze.dev/pkg/gooze/internal/model"
)

// MockWorkspace is an autogenerated mock type for the Workspace type
type MockWorkspace struct {
	mock.Mock
}

type MockWorkspace_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspace) EXPECT() *MockWorkspace_Expecter {
	return &MockWorkspace_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockWorkspace) Close(ctx context.Context) {
	_m.Called(ctx)
}

// MockWorkspace_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWorkspace_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWorkspace_Expecter) Close(ctx interface{}) *MockWorkspace_Close_Call {
	return &MockWorkspace_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockWorkspace_Close_Call) Run(run func(ctx context.Context)) *MockWorkspace_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWorkspace_Close_Call) Return() *MockWorkspace_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWorkspace_Close_Call) RunAndReturn(run func(context.Context)) *MockWorkspace_Close_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function with given fields: ctx, mutation
func (_m *MockWorkspace) Run(ctx context.Context, mutation model.Mutation) (model.Result, error) {
	ret := _m.Called(ctx, mutation)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 model.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Mutation) (model.Result, error)); ok {
		return rf(ctx, mutation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Mutation) model.Result); ok {
		r0 = rf(ctx, mutation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Mutation) error); ok {
		r1 = rf(ctx, mutation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkspace_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockWorkspace_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - mutation model.Mutation
func (_e *MockWorkspace_Expecter) Run(ctx interface{}, mutation interface{}) *MockWorkspace_Run_Call {
	return &MockWorkspace_Run_Call{Call: _e.mock.On("Run", ctx, mutation)}
}

func (_c *MockWorkspace_Run_Call) Run(run func(ctx context.Context, mutation model.Mutation)) *MockWorkspace_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mutation))
	})
	return _c
}

func (_c *MockWorkspace_Run_Call) Return(_a0 model.Result, _a1 error) *MockWorkspace_Run_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkspace_Run_Call) RunAndReturn(run func(context.Context, model.Mutation) (model.Result, error)) *MockWorkspace_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkspace creates a new instance of MockWorkspace. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspace(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspace {
	mock := &MockWorkspace{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
