// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "gooze.dev/pkg/gooze/internal/model"

	pkg "gooze.dev/pkg/gooze/pkg"
)

// MockReportManager is an autogenerated mock type for the ReportManager type
type MockReportManager struct {
	mock.Mock
}

type MockReportManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportManager) EXPECT() *MockReportManager_Expecter {
	return &MockReportManager_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, path
func (_m *MockReportManager) Load(ctx context.Context, path model.Path) ([]model.Report, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []model.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Path) ([]model.Report, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Path) []model.Report); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Path) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportManager_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockReportManager_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - path model.Path
func (_e *MockReportManager_Expecter) Load(ctx interface{}, path interface{}) *MockReportManager_Load_Call {
	return &MockReportManager_Load_Call{Call: _e.mock.On("Load", ctx, path)}
}

func (_c *MockReportManager_Load_Call) Run(run func(ctx context.Context, path model.Path)) *MockReportManager_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Path))
	})
	return _c
}

func (_c *MockReportManager_Load_Call) Return(_a0 []model.Report, _a1 error) *MockReportManager_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportManager_Load_Call) RunAndReturn(run func(context.Context, model.Path) ([]model.Report, error)) *MockReportManager_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ctx, basePath
func (_m *MockReportManager) Merge(ctx context.Context, basePath model.Path) error {
	ret := _m.Called(ctx, basePath)

	if len(ret) == 0 {
		panic("no return value specified for Merge")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Path) error); ok {
		r0 = rf(ctx, basePath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportManager_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type MockReportManager_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx context.Context
//   - basePath model.Path
func (_e *MockReportManager_Expecter) Merge(ctx interface{}, basePath interface{}) *MockReportManager_Merge_Call {
	return &MockReportManager_Merge_Call{Call: _e.mock.On("Merge", ctx, basePath)}
}

func (_c *MockReportManager_Merge_Call) Run(run func(ctx context.Context, basePath model.Path)) *MockReportManager_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Path))
	})
	return _c
}

func (_c *MockReportManager_Merge_Call) Return(_a0 error) *MockReportManager_Merge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportManager_Merge_Call) RunAndReturn(run func(context.Context, model.Path) error) *MockReportManager_Merge_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, reportsDir, reports
func (_m *MockReportManager) Save(ctx context.Context, reportsDir model.Path, reports pkg.FileSpill[model.Report]) error {
	ret := _m.Called(ctx, reportsDir, reports)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Path, pkg.FileSpill[model.Report]) error); ok {
		r0 = rf(ctx, reportsDir, reports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportManager_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockReportManager_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - reportsDir model.Path
//   - reports pkg.FileSpill[model.Report]
func (_e *MockReportManager_Expecter) Save(ctx interface{}, reportsDir interface{}, reports interface{}) *MockReportManager_Save_Call {
	return &MockReportManager_Save_Call{Call: _e.mock.On("Save", ctx, reportsDir, reports)}
}

func (_c *MockReportManager_Save_Call) Run(run func(ctx context.Context, reportsDir model.Path, reports pkg.FileSpill[model.Report])) *MockReportManager_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Path), args[2].(pkg.FileSpill[model.Report]))
	})
	return _c
}

func (_c *MockReportManager_Save_Call) Return(_a0 error) *MockReportManager_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportManager_Save_Call) RunAndReturn(run func(context.Context, model.Path, pkg.FileSpill[model.Report]) error) *MockReportManager_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveStream provides a mock function with given fields: ctx, reportsDir, reports
func (_m *MockReportManager) SaveStream(ctx context.Context, reportsDir model.Path, reports <-chan model.Report) error {
	ret := _m.Called(ctx, reportsDir, reports)

	if len(ret) == 0 {
		panic("no return value specified for SaveStream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Path, <-chan model.Report) error); ok {
		r0 = rf(ctx, reportsDir, reports)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportManager_SaveStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveStream'
type MockReportManager_SaveStream_Call struct {
	*mock.Call
}

// SaveStream is a helper method to define mock.On call
//   - ctx context.Context
//   - reportsDir model.Path
//   - reports <-chan model.Report
func (_e *MockReportManager_Expecter) SaveStream(ctx interface{}, reportsDir interface{}, reports interface{}) *MockReportManager_SaveStream_Call {
	return &MockReportManager_SaveStream_Call{Call: _e.mock.On("SaveStream", ctx, reportsDir, reports)}
}

func (_c *MockReportManager_SaveStream_Call) Run(run func(ctx context.Context, reportsDir model.Path, reports <-chan model.Report)) *MockReportManager_SaveStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Path), args[2].(<-chan model.Report))
	})
	return _c
}

func (_c *MockReportManager_SaveStream_Call) Return(_a0 error) *MockReportManager_SaveStream_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportManager_SaveStream_Call) RunAndReturn(run func(context.Context, model.Path, <-chan model.Report) error) *MockReportManager_SaveStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportManager creates a new instance of MockReportManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportManager {
	mock := &MockReportManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
