---
# Mockery configuration for generating mocks
with-expecter: true
disable-version-string: true
packages:
  gooze.dev/pkg/gooze/internal/domain:
    config:
      dir: internal/domain/mocks
      outpkg: mocks
    interfaces:
      Workflow:
      Orchestrator:
      Mutagen:
      MutationStreamer:
  gooze.dev/pkg/gooze/internal/adapter:
    config:
      dir: internal/adapter/mocks
      outpkg: mocks
    interfaces:
      GoFileAdapter:
      SourceFSAdapter:
      TestRunnerAdapter:
      ReportStore:
  gooze.dev/pkg/gooze/internal/controller:
    config:
      dir: internal/controller/mocks
      outpkg: mocks
    interfaces:
      UI:
