// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "gooze.dev/pkg/gooze/internal/model"
)

// MockEvents is an autogenerated mock type for the Events type
type MockEvents struct {
	mock.Mock
}

type MockEvents_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvents) EXPECT() *MockEvents_Expecter {
	return &MockEvents_Expecter{mock: &_m.Mock}
}

// Chan provides a mock function with no fields
func (_m *MockEvents) Chan() <-chan model.EventMsg {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Chan")
	}

	var r0 <-chan model.EventMsg
	if rf, ok := ret.Get(0).(func() <-chan model.EventMsg); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan model.EventMsg)
		}
	}

	return r0
}

// MockEvents_Chan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chan'
type MockEvents_Chan_Call struct {
	*mock.Call
}

// Chan is a helper method to define mock.On call
func (_e *MockEvents_Expecter) Chan() *MockEvents_Chan_Call {
	return &MockEvents_Chan_Call{Call: _e.mock.On("Chan")}
}

func (_c *MockEvents_Chan_Call) Run(run func()) *MockEvents_Chan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_Chan_Call) Return(_a0 <-chan model.EventMsg) *MockEvents_Chan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEvents_Chan_Call) RunAndReturn(run func() <-chan model.EventMsg) *MockEvents_Chan_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockEvents) Close() {
	_m.Called()
}

// MockEvents_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEvents_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEvents_Expecter) Close() *MockEvents_Close_Call {
	return &MockEvents_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEvents_Close_Call) Run(run func()) *MockEvents_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_Close_Call) Return() *MockEvents_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_Close_Call) RunAndReturn(run func()) *MockEvents_Close_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: err
func (_m *MockEvents) Error(err error) {
	_m.Called(err)
}

// MockEvents_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockEvents_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *MockEvents_Expecter) Error(err interface{}) *MockEvents_Error_Call {
	return &MockEvents_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *MockEvents_Error_Call) Run(run func(err error)) *MockEvents_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *MockEvents_Error_Call) Return() *MockEvents_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_Error_Call) RunAndReturn(run func(error)) *MockEvents_Error_Call {
	_c.Run(run)
	return _c
}

// Estimating provides a mock function with given fields: mutation
func (_m *MockEvents) Estimating(mutation model.Mutation) {
	_m.Called(mutation)
}

// MockEvents_Estimating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Estimating'
type MockEvents_Estimating_Call struct {
	*mock.Call
}

// Estimating is a helper method to define mock.On call
//   - mutation model.Mutation
func (_e *MockEvents_Expecter) Estimating(mutation interface{}) *MockEvents_Estimating_Call {
	return &MockEvents_Estimating_Call{Call: _e.mock.On("Estimating", mutation)}
}

func (_c *MockEvents_Estimating_Call) Run(run func(mutation model.Mutation)) *MockEvents_Estimating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Mutation))
	})
	return _c
}

func (_c *MockEvents_Estimating_Call) Return() *MockEvents_Estimating_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_Estimating_Call) RunAndReturn(run func(model.Mutation)) *MockEvents_Estimating_Call {
	_c.Run(run)
	return _c
}

// FinishEstimating provides a mock function with no fields
func (_m *MockEvents) FinishEstimating() {
	_m.Called()
}

// MockEvents_FinishEstimating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishEstimating'
type MockEvents_FinishEstimating_Call struct {
	*mock.Call
}

// FinishEstimating is a helper method to define mock.On call
func (_e *MockEvents_Expecter) FinishEstimating() *MockEvents_FinishEstimating_Call {
	return &MockEvents_FinishEstimating_Call{Call: _e.mock.On("FinishEstimating")}
}

func (_c *MockEvents_FinishEstimating_Call) Run(run func()) *MockEvents_FinishEstimating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_FinishEstimating_Call) Return() *MockEvents_FinishEstimating_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_FinishEstimating_Call) RunAndReturn(run func()) *MockEvents_FinishEstimating_Call {
	_c.Run(run)
	return _c
}

// FinishGeneratingMutations provides a mock function with no fields
func (_m *MockEvents) FinishGeneratingMutations() {
	_m.Called()
}

// MockEvents_FinishGeneratingMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishGeneratingMutations'
type MockEvents_FinishGeneratingMutations_Call struct {
	*mock.Call
}

// FinishGeneratingMutations is a helper method to define mock.On call
func (_e *MockEvents_Expecter) FinishGeneratingMutations() *MockEvents_FinishGeneratingMutations_Call {
	return &MockEvents_FinishGeneratingMutations_Call{Call: _e.mock.On("FinishGeneratingMutations")}
}

func (_c *MockEvents_FinishGeneratingMutations_Call) Run(run func()) *MockEvents_FinishGeneratingMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_FinishGeneratingMutations_Call) Return() *MockEvents_FinishGeneratingMutations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_FinishGeneratingMutations_Call) RunAndReturn(run func()) *MockEvents_FinishGeneratingMutations_Call {
	_c.Run(run)
	return _c
}

// FinishScanningPaths provides a mock function with no fields
func (_m *MockEvents) FinishScanningPaths() {
	_m.Called()
}

// MockEvents_FinishScanningPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishScanningPaths'
type MockEvents_FinishScanningPaths_Call struct {
	*mock.Call
}

// FinishScanningPaths is a helper method to define mock.On call
func (_e *MockEvents_Expecter) FinishScanningPaths() *MockEvents_FinishScanningPaths_Call {
	return &MockEvents_FinishScanningPaths_Call{Call: _e.mock.On("FinishScanningPaths")}
}

func (_c *MockEvents_FinishScanningPaths_Call) Run(run func()) *MockEvents_FinishScanningPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_FinishScanningPaths_Call) Return() *MockEvents_FinishScanningPaths_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_FinishScanningPaths_Call) RunAndReturn(run func()) *MockEvents_FinishScanningPaths_Call {
	_c.Run(run)
	return _c
}

// GeneratingMutationsFor provides a mock function with given fields: source
func (_m *MockEvents) GeneratingMutationsFor(source model.Source) {
	_m.Called(source)
}

// MockEvents_GeneratingMutationsFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GeneratingMutationsFor'
type MockEvents_GeneratingMutationsFor_Call struct {
	*mock.Call
}

// GeneratingMutationsFor is a helper method to define mock.On call
//   - source model.Source
func (_e *MockEvents_Expecter) GeneratingMutationsFor(source interface{}) *MockEvents_GeneratingMutationsFor_Call {
	return &MockEvents_GeneratingMutationsFor_Call{Call: _e.mock.On("GeneratingMutationsFor", source)}
}

func (_c *MockEvents_GeneratingMutationsFor_Call) Run(run func(source model.Source)) *MockEvents_GeneratingMutationsFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Source))
	})
	return _c
}

func (_c *MockEvents_GeneratingMutationsFor_Call) Return() *MockEvents_GeneratingMutationsFor_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_GeneratingMutationsFor_Call) RunAndReturn(run func(model.Source)) *MockEvents_GeneratingMutationsFor_Call {
	_c.Run(run)
	return _c
}

// PairFound provides a mock function with given fields: source
func (_m *MockEvents) PairFound(source model.Source) {
	_m.Called(source)
}

// MockEvents_PairFound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PairFound'
type MockEvents_PairFound_Call struct {
	*mock.Call
}

// PairFound is a helper method to define mock.On call
//   - source model.Source
func (_e *MockEvents_Expecter) PairFound(source interface{}) *MockEvents_PairFound_Call {
	return &MockEvents_PairFound_Call{Call: _e.mock.On("PairFound", source)}
}

func (_c *MockEvents_PairFound_Call) Run(run func(source model.Source)) *MockEvents_PairFound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Source))
	})
	return _c
}

func (_c *MockEvents_PairFound_Call) Return() *MockEvents_PairFound_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_PairFound_Call) RunAndReturn(run func(model.Source)) *MockEvents_PairFound_Call {
	_c.Run(run)
	return _c
}

// ScanningPath provides a mock function with given fields: path
func (_m *MockEvents) ScanningPath(path model.Path) {
	_m.Called(path)
}

// MockEvents_ScanningPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanningPath'
type MockEvents_ScanningPath_Call struct {
	*mock.Call
}

// ScanningPath is a helper method to define mock.On call
//   - path model.Path
func (_e *MockEvents_Expecter) ScanningPath(path interface{}) *MockEvents_ScanningPath_Call {
	return &MockEvents_ScanningPath_Call{Call: _e.mock.On("ScanningPath", path)}
}

func (_c *MockEvents_ScanningPath_Call) Run(run func(path model.Path)) *MockEvents_ScanningPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Path))
	})
	return _c
}

func (_c *MockEvents_ScanningPath_Call) Return() *MockEvents_ScanningPath_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_ScanningPath_Call) RunAndReturn(run func(model.Path)) *MockEvents_ScanningPath_Call {
	_c.Run(run)
	return _c
}

// ShowEstimationResult provides a mock function with given fields: result
func (_m *MockEvents) ShowEstimationResult(result map[string]struct {
	Count  int
	Source model.Source
}) {
	_m.Called(result)
}

// MockEvents_ShowEstimationResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowEstimationResult'
type MockEvents_ShowEstimationResult_Call struct {
	*mock.Call
}

// ShowEstimationResult is a helper method to define mock.On call
//   - result map[string]struct{Count int;Source model.Source}
func (_e *MockEvents_Expecter) ShowEstimationResult(result interface{}) *MockEvents_ShowEstimationResult_Call {
	return &MockEvents_ShowEstimationResult_Call{Call: _e.mock.On("ShowEstimationResult", result)}
}

func (_c *MockEvents_ShowEstimationResult_Call) Run(run func(result map[string]struct {
	Count  int
	Source model.Source
})) *MockEvents_ShowEstimationResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]struct {
			Count  int
			Source model.Source
		}))
	})
	return _c
}

func (_c *MockEvents_ShowEstimationResult_Call) Return() *MockEvents_ShowEstimationResult_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_ShowEstimationResult_Call) RunAndReturn(run func(map[string]struct {
	Count  int
	Source model.Source
})) *MockEvents_ShowEstimationResult_Call {
	_c.Run(run)
	return _c
}

// StartEstimating provides a mock function with no fields
func (_m *MockEvents) StartEstimating() {
	_m.Called()
}

// MockEvents_StartEstimating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEstimating'
type MockEvents_StartEstimating_Call struct {
	*mock.Call
}

// StartEstimating is a helper method to define mock.On call
func (_e *MockEvents_Expecter) StartEstimating() *MockEvents_StartEstimating_Call {
	return &MockEvents_StartEstimating_Call{Call: _e.mock.On("StartEstimating")}
}

func (_c *MockEvents_StartEstimating_Call) Run(run func()) *MockEvents_StartEstimating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_StartEstimating_Call) Return() *MockEvents_StartEstimating_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_StartEstimating_Call) RunAndReturn(run func()) *MockEvents_StartEstimating_Call {
	_c.Run(run)
	return _c
}

// StartGeneratingMutations provides a mock function with no fields
func (_m *MockEvents) StartGeneratingMutations() {
	_m.Called()
}

// MockEvents_StartGeneratingMutations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartGeneratingMutations'
type MockEvents_StartGeneratingMutations_Call struct {
	*mock.Call
}

// StartGeneratingMutations is a helper method to define mock.On call
func (_e *MockEvents_Expecter) StartGeneratingMutations() *MockEvents_StartGeneratingMutations_Call {
	return &MockEvents_StartGeneratingMutations_Call{Call: _e.mock.On("StartGeneratingMutations")}
}

func (_c *MockEvents_StartGeneratingMutations_Call) Run(run func()) *MockEvents_StartGeneratingMutations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_StartGeneratingMutations_Call) Return() *MockEvents_StartGeneratingMutations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_StartGeneratingMutations_Call) RunAndReturn(run func()) *MockEvents_StartGeneratingMutations_Call {
	_c.Run(run)
	return _c
}

// StartScanningPaths provides a mock function with no fields
func (_m *MockEvents) StartScanningPaths() {
	_m.Called()
}

// MockEvents_StartScanningPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartScanningPaths'
type MockEvents_StartScanningPaths_Call struct {
	*mock.Call
}

// StartScanningPaths is a helper method to define mock.On call
func (_e *MockEvents_Expecter) StartScanningPaths() *MockEvents_StartScanningPaths_Call {
	return &MockEvents_StartScanningPaths_Call{Call: _e.mock.On("StartScanningPaths")}
}

func (_c *MockEvents_StartScanningPaths_Call) Run(run func()) *MockEvents_StartScanningPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvents_StartScanningPaths_Call) Return() *MockEvents_StartScanningPaths_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEvents_StartScanningPaths_Call) RunAndReturn(run func()) *MockEvents_StartScanningPaths_Call {
	_c.Run(run)
	return _c
}

// NewMockEvents creates a new instance of MockEvents. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvents(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvents {
	mock := &MockEvents{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
