// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "gooze.dev/pkg/gooze/internal/domain"

	mock "github.com/stretchr/testify/mock"

	model "gooze.dev/pkg/gooze/internal/model"
)

// MockUI is an autogenerated mock type for the UI type
type MockUI struct {
	mock.Mock
}

type MockUI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUI) EXPECT() *MockUI_Expecter {
	return &MockUI_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *MockUI) Close(ctx context.Context) {
	_m.Called(ctx)
}

// MockUI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockUI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUI_Expecter) Close(ctx interface{}) *MockUI_Close_Call {
	return &MockUI_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockUI_Close_Call) Run(run func(ctx context.Context)) *MockUI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUI_Close_Call) Return() *MockUI_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_Close_Call) RunAndReturn(run func(context.Context)) *MockUI_Close_Call {
	_c.Run(run)
	return _c
}

// DisplayCompletedTestInfo provides a mock function with given fields: ctx, currentMutation, mutationResult
func (_m *MockUI) DisplayCompletedTestInfo(ctx context.Context, currentMutation model.Mutation, mutationResult model.Result) {
	_m.Called(ctx, currentMutation, mutationResult)
}

// MockUI_DisplayCompletedTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayCompletedTestInfo'
type MockUI_DisplayCompletedTestInfo_Call struct {
	*mock.Call
}

// DisplayCompletedTestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - currentMutation model.Mutation
//   - mutationResult model.Result
func (_e *MockUI_Expecter) DisplayCompletedTestInfo(ctx interface{}, currentMutation interface{}, mutationResult interface{}) *MockUI_DisplayCompletedTestInfo_Call {
	return &MockUI_DisplayCompletedTestInfo_Call{Call: _e.mock.On("DisplayCompletedTestInfo", ctx, currentMutation, mutationResult)}
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) Run(run func(ctx context.Context, currentMutation model.Mutation, mutationResult model.Result)) *MockUI_DisplayCompletedTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mutation), args[2].(model.Result))
	})
	return _c
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) Return() *MockUI_DisplayCompletedTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayCompletedTestInfo_Call) RunAndReturn(run func(context.Context, model.Mutation, model.Result)) *MockUI_DisplayCompletedTestInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayConcurrencyInfo provides a mock function with given fields: ctx, threads, shardIndex, shardCount
func (_m *MockUI) DisplayConcurrencyInfo(ctx context.Context, threads int, shardIndex int, shardCount int) {
	_m.Called(ctx, threads, shardIndex, shardCount)
}

// MockUI_DisplayConcurrencyInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayConcurrencyInfo'
type MockUI_DisplayConcurrencyInfo_Call struct {
	*mock.Call
}

// DisplayConcurrencyInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - threads int
//   - shardIndex int
//   - shardCount int
func (_e *MockUI_Expecter) DisplayConcurrencyInfo(ctx interface{}, threads interface{}, shardIndex interface{}, shardCount interface{}) *MockUI_DisplayConcurrencyInfo_Call {
	return &MockUI_DisplayConcurrencyInfo_Call{Call: _e.mock.On("DisplayConcurrencyInfo", ctx, threads, shardIndex, shardCount)}
}

func (_c *MockUI_DisplayConcurrencyInfo_Call) Run(run func(ctx context.Context, threads int, shardIndex int, shardCount int)) *MockUI_DisplayConcurrencyInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUI_DisplayConcurrencyInfo_Call) Return() *MockUI_DisplayConcurrencyInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayConcurrencyInfo_Call) RunAndReturn(run func(context.Context, int, int, int)) *MockUI_DisplayConcurrencyInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayEstimation provides a mock function with given fields: ctx, estimation, err
func (_m *MockUI) DisplayEstimation(ctx context.Context, estimation domain.Estimation, err error) error {
	ret := _m.Called(ctx, estimation, err)

	if len(ret) == 0 {
		panic("no return value specified for DisplayEstimation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Estimation, error) error); ok {
		r0 = rf(ctx, estimation, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_DisplayEstimation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayEstimation'
type MockUI_DisplayEstimation_Call struct {
	*mock.Call
}

// DisplayEstimation is a helper method to define mock.On call
//   - ctx context.Context
//   - estimation domain.Estimation
//   - err error
func (_e *MockUI_Expecter) DisplayEstimation(ctx interface{}, estimation interface{}, err interface{}) *MockUI_DisplayEstimation_Call {
	return &MockUI_DisplayEstimation_Call{Call: _e.mock.On("DisplayEstimation", ctx, estimation, err)}
}

func (_c *MockUI_DisplayEstimation_Call) Run(run func(ctx context.Context, estimation domain.Estimation, err error)) *MockUI_DisplayEstimation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Estimation), args[2].(error))
	})
	return _c
}

func (_c *MockUI_DisplayEstimation_Call) Return(_a0 error) *MockUI_DisplayEstimation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_DisplayEstimation_Call) RunAndReturn(run func(context.Context, domain.Estimation, error) error) *MockUI_DisplayEstimation_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayMutationScore provides a mock function with given fields: ctx, score
func (_m *MockUI) DisplayMutationScore(ctx context.Context, score float64) {
	_m.Called(ctx, score)
}

// MockUI_DisplayMutationScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayMutationScore'
type MockUI_DisplayMutationScore_Call struct {
	*mock.Call
}

// DisplayMutationScore is a helper method to define mock.On call
//   - ctx context.Context
//   - score float64
func (_e *MockUI_Expecter) DisplayMutationScore(ctx interface{}, score interface{}) *MockUI_DisplayMutationScore_Call {
	return &MockUI_DisplayMutationScore_Call{Call: _e.mock.On("DisplayMutationScore", ctx, score)}
}

func (_c *MockUI_DisplayMutationScore_Call) Run(run func(ctx context.Context, score float64)) *MockUI_DisplayMutationScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64))
	})
	return _c
}

func (_c *MockUI_DisplayMutationScore_Call) Return() *MockUI_DisplayMutationScore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayMutationScore_Call) RunAndReturn(run func(context.Context, float64)) *MockUI_DisplayMutationScore_Call {
	_c.Run(run)
	return _c
}

// DisplayStartingTestInfo provides a mock function with given fields: ctx, currentMutation, threadID
func (_m *MockUI) DisplayStartingTestInfo(ctx context.Context, currentMutation model.Mutation, threadID int) {
	_m.Called(ctx, currentMutation, threadID)
}

// MockUI_DisplayStartingTestInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayStartingTestInfo'
type MockUI_DisplayStartingTestInfo_Call struct {
	*mock.Call
}

// DisplayStartingTestInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - currentMutation model.Mutation
//   - threadID int
func (_e *MockUI_Expecter) DisplayStartingTestInfo(ctx interface{}, currentMutation interface{}, threadID interface{}) *MockUI_DisplayStartingTestInfo_Call {
	return &MockUI_DisplayStartingTestInfo_Call{Call: _e.mock.On("DisplayStartingTestInfo", ctx, currentMutation, threadID)}
}

func (_c *MockUI_DisplayStartingTestInfo_Call) Run(run func(ctx context.Context, currentMutation model.Mutation, threadID int)) *MockUI_DisplayStartingTestInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mutation), args[2].(int))
	})
	return _c
}

func (_c *MockUI_DisplayStartingTestInfo_Call) Return() *MockUI_DisplayStartingTestInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayStartingTestInfo_Call) RunAndReturn(run func(context.Context, model.Mutation, int)) *MockUI_DisplayStartingTestInfo_Call {
	_c.Run(run)
	return _c
}

// DisplayUpcomingTestsInfo provides a mock function with given fields: ctx, i
func (_m *MockUI) DisplayUpcomingTestsInfo(ctx context.Context, i int) {
	_m.Called(ctx, i)
}

// MockUI_DisplayUpcomingTestsInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayUpcomingTestsInfo'
type MockUI_DisplayUpcomingTestsInfo_Call struct {
	*mock.Call
}

// DisplayUpcomingTestsInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - i int
func (_e *MockUI_Expecter) DisplayUpcomingTestsInfo(ctx interface{}, i interface{}) *MockUI_DisplayUpcomingTestsInfo_Call {
	return &MockUI_DisplayUpcomingTestsInfo_Call{Call: _e.mock.On("DisplayUpcomingTestsInfo", ctx, i)}
}

func (_c *MockUI_DisplayUpcomingTestsInfo_Call) Run(run func(ctx context.Context, i int)) *MockUI_DisplayUpcomingTestsInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUI_DisplayUpcomingTestsInfo_Call) Return() *MockUI_DisplayUpcomingTestsInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_DisplayUpcomingTestsInfo_Call) RunAndReturn(run func(context.Context, int)) *MockUI_DisplayUpcomingTestsInfo_Call {
	_c.Run(run)
	return _c
}

// StartEstimate provides a mock function with given fields: ctx
func (_m *MockUI) StartEstimate(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartEstimate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_StartEstimate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartEstimate'
type MockUI_StartEstimate_Call struct {
	*mock.Call
}

// StartEstimate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUI_Expecter) StartEstimate(ctx interface{}) *MockUI_StartEstimate_Call {
	return &MockUI_StartEstimate_Call{Call: _e.mock.On("StartEstimate", ctx)}
}

func (_c *MockUI_StartEstimate_Call) Run(run func(ctx context.Context)) *MockUI_StartEstimate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUI_StartEstimate_Call) Return(_a0 error) *MockUI_StartEstimate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_StartEstimate_Call) RunAndReturn(run func(context.Context) error) *MockUI_StartEstimate_Call {
	_c.Call.Return(run)
	return _c
}

// StartTest provides a mock function with given fields: ctx
func (_m *MockUI) StartTest(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartTest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUI_StartTest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTest'
type MockUI_StartTest_Call struct {
	*mock.Call
}

// StartTest is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUI_Expecter) StartTest(ctx interface{}) *MockUI_StartTest_Call {
	return &MockUI_StartTest_Call{Call: _e.mock.On("StartTest", ctx)}
}

func (_c *MockUI_StartTest_Call) Run(run func(ctx context.Context)) *MockUI_StartTest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUI_StartTest_Call) Return(_a0 error) *MockUI_StartTest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUI_StartTest_Call) RunAndReturn(run func(context.Context) error) *MockUI_StartTest_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function with given fields: ctx
func (_m *MockUI) Wait(ctx context.Context) {
	_m.Called(ctx)
}

// MockUI_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockUI_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUI_Expecter) Wait(ctx interface{}) *MockUI_Wait_Call {
	return &MockUI_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockUI_Wait_Call) Run(run func(ctx context.Context)) *MockUI_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUI_Wait_Call) Return() *MockUI_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUI_Wait_Call) RunAndReturn(run func(context.Context)) *MockUI_Wait_Call {
	_c.Run(run)
	return _c
}

// NewMockUI creates a new instance of MockUI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUI {
	mock := &MockUI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
